export {
  SCHEMA_VERSION,
  PEP_INTERFACE_VERSION,
  MGMT_API_VERSION,
  GovernanceProfile,
  Phase,
  ApprovalMode,
  DeploymentTarget,
  ShellMode,
  MandateStatus,
  TERMINAL_STATES,
  ToolPolicyConstraints,
  ToolPolicy,
  DeploymentPermissions,
  DatabasePermissions,
  ShellPermissions,
  PackagePermissions,
  ExternalApiPermissions,
  SecretPermissions,
  PlatformPermissions,
  Budget,
  SessionLimits,
  DelegationChainEntry,
  PoAParties,
  PoAScope,
  PoARequirements,
  PoACredential,
  CredentialFormat,
  ActionDescriptor,
  AgentIdentity,
  CredentialReference,
  SessionState,
  LiveMandateState,
  EnforcementContext,
  EnforcementRequest,
  EnforcementDecisionType,
  EnforcementMode,
  CheckResultOutcome,
  ViolationSeverity,
  VIOLATION_CODES,
  PEP_ERROR_CODES,
  MGMT_ERROR_CODES,
  CORE_VERBS,
  PHASE_VERB_MAP,
  DEFAULT_GOVERNANCE_CEILINGS,
  GOVERNANCE_RESTRICTED_TRANSACTIONS,
  GOVERNANCE_RESTRICTED_DECISIONS,
  ApprovalEvidence,
  TariffCode,
  LicenseType,
  AdapterType,
  ConnectorSlotName,
  ConnectorSlotStatus,
  AvailabilityCode,
  CONNECTOR_SLOT_CONFIGS,
  DEPLOYMENT_POLICY_MATRIX,
  DEFAULT_CUSTOMER_LICENSE_STATE,
  tariffEffectiveLevel,
} from "./types.js";

export type {
  BaseTariffCode,
  CheckResult,
  EnforcedConstraint,
  Violation,
  AuditRecord,
  EnforcementDecision,
  BatchDecision,
  EnforcementPolicy,
  EnforcementError,
  ViolationCode,
  PepErrorCode,
  MgmtErrorCode,
  ManagementError,
  MandateAuditEntry,
  MandateCreationRequest,
  MandateCreationResponse,
  MandateActivationRequest,
  MandateActivationResponse,
  MandateRevocationRequest,
  MandateRevocationResponse,
  MandateSuspensionRequest,
  MandateSuspensionResponse,
  MandateResumptionRequest,
  MandateResumptionResponse,
  MandateDetail,
  MandateQueryRequest,
  MandateQueryResponse,
  BudgetTopUpRequest,
  BudgetTopUpResponse,
  BudgetConsumptionReport,
  TTLExtensionRequest,
  TTLExtensionResponse,
  DelegationRequest,
  DelegationResponse,
  GovernanceProfileCeiling,
  GAuthJWTClaims,
  MandateStore,
  AdapterHealthResult,
  ConnectorSlotConfig,
  DeploymentPolicyMatrix,
  TariffGateResult,
  SealedAdapterManifest,
  CustomerLicenseState,
  S2SAuthHeaders,
  PoaMapSummary,
  ComplianceAuditEntry,
  W3cVcCredentialSubject,
  W3cVerifiableCredential,
  W3cDataIntegrityProof,
  W3cVerifiablePresentation,
  BitstringStatusListEntry,
  SelectiveDisclosureFrame,
  OpenID4VCICredentialOffer,
  OpenID4VPPresentationRequest,
} from "./types.js";

export {
  canonicalJson,
  sha256Hex,
  computeScopeChecksum,
  computeToolPermissionsHash,
  computePlatformPermissionsHash,
  matchGlob,
} from "./crypto.js";

export {
  createExtendedToken,
  validateExtendedToken,
  GAuthTokenError,
} from "./token.js";
export type { TokenCreationOptions, TokenValidationOptions, ValidatedToken } from "./token.js";

export {
  enforceAction,
  batchEnforce,
  getEnforcementPolicy,
  isEnforcementError,
} from "./pep.js";
export type { PEPOptions } from "./pep.js";

export {
  ManagementAPI,
  InMemoryMandateStore,
  isManagementError,
} from "./management.js";

export {
  AdapterRegistry,
  AdapterRegistrationError,
  ConnectorSlotRegistry,
  type TrustKeyEntry,
  NoOpPolicyDecisionAdapter,
  NoOpOAuthEngineAdapter,
  NoOpFoundryAdapter,
  NoOpWalletAdapter,
  NoOpGovernanceAdapter,
  NoOpWeb3IdentityAdapter,
  NoOpDNAIdentityAdapter,
  NoOpBillingAdapter,
  createDefaultRegistry,
  computeS2SHeaders,
  verifyS2SSignature,
} from "./adapters.js";
export type {
  PolicyDecisionAdapter,
  OAuthEngineAdapter,
  FoundryAdapter,
  WalletAdapter,
  GovernanceAdapter,
  Web3IdentityAdapter,
  DNAIdentityAdapter,
  BillingAdapter,
  GAuthAdapter,
  AdapterRegistrationOptions,
  ConnectorSlotState,
} from "./adapters.js";

export {
  poaToVerifiableCredential,
  mandateToVerifiableCredential,
  createVerifiablePresentation,
  createDataIntegrityProof,
  attachProof,
  attachPresentationProof,
  resolveDid,
  createBitstringStatusListEntry,
  createSelectiveDisclosureFrame,
  createCredentialOffer,
  createPresentationRequest,
  validateVerifiableCredential,
  validateVerifiablePresentation,
} from "./vc.js";
export type { PoaToVcOptions } from "./vc.js";

export {
  handlePEPRequest,
  handleMgmtRequest,
} from "./http.js";
export type {
  PEPHttpRequest,
  PEPHttpResponse,
  MgmtHttpRequest,
  MgmtHttpResponse,
} from "./http.js";
